baseurl: /
languageCode: en-US
title: Life is short. Write for eternity.
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About me
      url: /about/
    - name: GitHub
      url: https://github.com/QingZhao0512
    - name: Twitter
      url: https://twitter.com/watermelon_zq?t=GK-vE9p3Z1lxBrqPNYO2TQ&s=09
    - name: CV  
      url: "files/CV_QingZhao_230812.pdf"
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: logo
    height: 50
    url: avatar.jpg
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
